import { NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { requireUser, errorResponse, HttpError } from "@/lib/session";
import { scanSchema } from "@/lib/validation";
import { audit } from "@/lib/audit";

export const dynamic = "force-dynamic";

/**
 * Status-driven scan endpoint. The action is inferred from the item's current
 * status (not supplied by the client):
 *   GENERATED     -> ENTRY  (item enters the warehouse)
 *   IN_WAREHOUSE  -> EXIT   (item shipped to a store; storeId required)
 *   EXITED        -> rejected (single-use lifecycle is terminal)
 * The status update and the immutable movement record are written in one
 * transaction so the ledger can never diverge from the item state.
 */
export async function POST(req: Request, { params }: { params: { code: string } }) {
  try {
    const user = await requireUser();
    const code = decodeURIComponent(params.code).trim();

    let body: unknown = {};
    try {
      body = await req.json();
    } catch {
      // Empty body is valid for ENTRY scans.
    }
    const { storeId } = scanSchema.parse(body ?? {});

    const result = await prisma.$transaction(async (tx) => {
      const item = await tx.item.findUnique({ where: { code } });
      if (!item) {
        throw new HttpError(404, "Unknown code. This item was not generated by the system.");
      }

      if (item.status === "EXITED") {
        throw new HttpError(
          409,
          "This item has already exited the warehouse. Codes are single-use and cannot re-enter."
        );
      }

      if (item.status === "GENERATED") {
        // ENTRY
        const updated = await tx.item.update({
          where: { id: item.id },
          data: { status: "IN_WAREHOUSE", enteredAt: new Date() },
        });
        await tx.movement.create({
          data: {
            itemId: item.id,
            productId: item.productId,
            warehouseId: item.warehouseId,
            type: "ENTRY",
            scannedById: user.id,
          },
        });
        return { action: "ENTRY" as const, item: updated };
      }

      // status === "IN_WAREHOUSE" -> EXIT
      if (!storeId) {
        throw new HttpError(400, "A destination store is required to exit this item.");
      }
      const store = await tx.store.findUnique({ where: { id: storeId } });
      if (!store) throw new HttpError(404, "Destination store not found.");

      const updated = await tx.item.update({
        where: { id: item.id },
        data: { status: "EXITED", exitedAt: new Date(), storeId },
      });
      await tx.movement.create({
        data: {
          itemId: item.id,
          productId: item.productId,
          warehouseId: item.warehouseId,
          type: "EXIT",
          storeId,
          scannedById: user.id,
        },
      });
      return { action: "EXIT" as const, item: updated };
    });

    await audit({
      actorUserId: user.id,
      action: result.action === "ENTRY" ? "scan_entry" : "scan_exit",
      entity: "item",
      entityId: result.item.id,
      metadata: { code, storeId: storeId ?? null },
    });

    return NextResponse.json(result);
  } catch (err) {
    if (err instanceof Error && err.name === "ZodError") {
      return NextResponse.json({ error: "Invalid scan request." }, { status: 400 });
    }
    return errorResponse(err);
  }
}
