import { NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { requireUser, errorResponse, HttpError } from "@/lib/session";

export const dynamic = "force-dynamic";

const NEXT_ACTION: Record<string, "ENTRY" | "EXIT" | null> = {
  GENERATED: "ENTRY",
  IN_WAREHOUSE: "EXIT",
  EXITED: null,
};

export async function GET(_req: Request, { params }: { params: { code: string } }) {
  try {
    await requireUser();
    const code = decodeURIComponent(params.code).trim();
    const item = await prisma.item.findUnique({
      where: { code },
      include: {
        product: { select: { name: true, codePrefix: true, unit: true } },
        warehouse: { select: { name: true } },
        store: { select: { name: true } },
        movements: {
          orderBy: { scannedAt: "desc" },
          include: {
            store: { select: { name: true } },
            scannedBy: { select: { name: true, email: true } },
          },
        },
      },
    });
    if (!item) throw new HttpError(404, "Unknown code. This item was not generated by the system.");

    return NextResponse.json({
      item,
      nextAction: NEXT_ACTION[item.status] ?? null,
    });
  } catch (err) {
    return errorResponse(err);
  }
}
